# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14dEtkITH8fos6fsQb7Yu_FhBLqL879wf
"""

import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA

# setting streamlit web page
st.set_page_config(page_title="Flight Route Clustering", layout="wide")

# load data
df = pd.read_csv("Air_Traffic_Passenger_Statistics.csv")

# tranfrom date
df['Activity Period'] = pd.to_datetime(df['Activity Period'], errors='coerce', format='%Y%m')
df = df.dropna(subset=["Activity Period"])

# create Year, Month, Route
df['Year'] = df['Activity Period'].dt.year
df['Month'] = df['Activity Period'].dt.month
df['Route'] = df['Operating Airline'] + " to " + df['GEO Region']

# create title
st.title("✈️ Flight Route Clustering for Optimization")

# create sidebar
with st.sidebar:
    st.header("🔧 Clustering Configuration")
    k = st.slider("Select number of clusters (k)", 2, 10, 3)

# Include route information
route_group = df.groupby("Route").agg(
    avg_passenger_per_month=("Passenger Count", "mean"),
    std_passenger=("Passenger Count", "std"),
    total_passenger=("Passenger Count", "sum")
).reset_index()

# drop miissing valua
route_group.dropna(inplace=True)

# Standardize data before clustering
features = ['avg_passenger_per_month', 'std_passenger', 'total_passenger']
scaler = StandardScaler()
X_scaled = scaler.fit_transform(route_group[features])

# KMeans
kmeans = KMeans(n_clusters=k, random_state=42, n_init=10)
route_group['Cluster'] = kmeans.fit_predict(X_scaled)

# PCA for visualization
pca = PCA(n_components=2)
pca_result = pca.fit_transform(X_scaled)
route_group['PCA1'] = pca_result[:, 0]
route_group['PCA2'] = pca_result[:, 1]


# Scatter Plot
fig, ax = plt.subplots(figsize=(8, 5))
sns.scatterplot(data=route_group, x='PCA1', y='PCA2', hue='Cluster', palette='tab10', s=100)
plt.title("Cluster Visualization (PCA)")
plt.xlabel("PCA 1")
plt.ylabel("PCA 2")
st.pyplot(fig)